In [17]:
# array函数
import numpy as np
a = np.array([1,2,3])
a = np.array([[1,2],[3,4]])
a = np.array([1,2,3], dtype = complex)    

In [18]:
# zeros函数
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# ones函数
np.ones((2,3))


array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# eye函数
np.eye(10)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:
# arange函数
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# NumPy数据类型举例
a = np.array([1,2,3], dtype=np.float64)
a = np.array([1,2,3], dtype=np.int32)
a = np.array(['abc', 'defg'], dtype=np.string_)

In [23]:
# 对数据进行批量运算，不需要写循环
a = np.array([1,2,3])
print(a * a)
print(a + a)
print(1/a)

a=np.arange(10)
print(np.sqrt(a))
print(np.exp(a))

b=np.random.randn(10)
c = np.add(a, b)
d = np.maximum(b, c)

[1 4 9]
[2 4 6]
[1.         0.5        0.33333333]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [24]:
# 一维数组
arr = np.arange(10)
arr[5:8] # 切片
arr[5:8] = 12 # 赋值

# 高维数组
arr2d = np.arange(9).reshape((3,3))
arr2d[2] # 输出一维数组
arr2d[0][2]
arr2d[0, 2]

2

In [25]:
# 数据统计
arr = np.array([3, 2, 4, 1])
arr.mean() # 计算平均值
arr.sum() # 求和
arr.std() # 计算方差
arr.min() # 求最小值
arr.argmin() # 求最小值的索引
arr.cumsum() # 累积求和
(arr>1).sum() # 大于1的个数
(arr>1).any() # 是否存在大于1的元素
(arr>1).all() # 是否所有元素都大于1

False

In [26]:
# 随机数生成

a = np.random.randn(3, 4) # 标准正态分布
a = np.random.randint(10, size=5) # 整数
a = np.random.poisson(5, 1000) # 泊松分布

arr = ['a', 'b', 'c', 'd', 'e']
np.random.choice(arr, 4, (0.1, 0, 0.3, 0.6, 0))

array(['a', 'b', 'e', 'e'], dtype='<U1')

In [27]:
# 实战数据
np.random.seed(1)
values = np.random.randn(1000).cumsum()

In [28]:
# 实现
i = np.argmax(np.maximum.accumulate(values) - values)
j = np.argmax(values[:i+1])
print(i, j)

790 599


In [1]:
# 实战 - 用Pandas分析链家房价

In [1]:
import pymongo
import pandas as pd
client = pymongo.MongoClient()
db = client["house"]
cursor = db.house.find()
df = pd.DataFrame(list(cursor))
df.drop_duplicates(inplace=True) 

ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused