In [1]:
import numpy as np
np.ones(5)

array([1., 1., 1., 1., 1.])

In [3]:
import numpy as np
a = np.array([1,2,3])
a = np.array([[1,2],[3,4]])
a = np.array([1,2,3], dtype = complex)
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [4]:
a.shape

(3,)

In [5]:
a.dtype

dtype('complex128')

In [6]:
a.ndim

1

In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a = np.array([1,2,3], dtype=np.float64)
print(a.dtype)
print(a)

float64
[1. 2. 3.]


In [16]:
a = np.array([1,2,3], dtype=np.int32)
print(a.dtype)
print(a)

int32
[1 2 3]


In [18]:
a = np.array(['abc', 'defg'], dtype='S3')
print(a.dtype)
print(a)

|S3
[b'abc' b'def']


In [19]:
a = np.array([1,2,3])
print(a * a)
print(a + a)
print(1/a)


[1 4 9]
[2 4 6]
[1.         0.5        0.33333333]


In [20]:
a=np.arange(10)
print(np.sqrt(a))
print(np.exp(a))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [22]:
b=np.random.randn(10)
c = np.add(a, b)
d = np.maximum(b, c)
print(c)
print(d)

[-1.72997364  2.14460723  2.72636085  3.91107254  2.29672706  5.22877172
  6.29683723  7.47743847  7.85131897  8.84049029]
[-1.72997364  2.14460723  2.72636085  3.91107254  2.29672706  5.22877172
  6.29683723  7.47743847  7.85131897  8.84049029]


In [23]:
arr2d = np.arange(9).reshape((3,3))
print(arr2d)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [24]:
print(arr2d[2]) # 输出一维数组
print(arr2d[0][2])
print(arr2d[0, 2])

[6 7 8]
2
2


In [26]:
arr2d[arr2d<5]

array([0, 1, 2, 3, 4])

In [27]:
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
arr = np.array([3, 2, 4, 1])
arr

array([3, 2, 4, 1])

In [29]:
arr.sum()

10

In [30]:
arr.mean()

2.5

In [31]:
arr.std()

1.118033988749895

In [32]:
arr.min()

1

In [33]:
arr.max()

4

In [34]:
arr.argmax()

2

In [35]:
arr.cumsum()

array([ 3,  5,  9, 10], dtype=int32)

In [36]:
(arr>1).sum()

3

In [37]:
(arr>1).any()

True

In [38]:
(arr>1).all()

False

In [40]:
a = np.random.randn(3, 4) # 标准正态分布
a

array([[ 0.73904612, -1.09928527,  0.12436162,  1.36815876],
       [-1.81888579,  0.45889662,  1.44615061, -0.79951403],
       [ 1.12773341,  0.92725402,  0.45645693, -0.31430252]])

In [41]:
a = np.random.randint(10, size=5) # 整数
a

array([5, 1, 5, 7, 7])

In [42]:
a = np.random.poisson(5, 1000) # 泊松分布
a

array([ 4,  4,  4,  5,  5,  0,  3,  4,  8,  3,  7,  6,  6,  5,  8,  7,  5,
        5,  5,  5,  5,  3,  5,  3,  9,  4,  9,  3,  4,  4,  5,  6,  3,  5,
        6,  4,  3,  4,  4,  5,  5,  4,  6,  6,  4,  2,  4,  3,  6,  5,  2,
        4,  3,  4,  5,  6,  4,  8,  3,  6,  2,  8,  1,  8,  5,  4,  1,  3,
        4,  4,  8,  6,  2,  6,  6,  8,  3,  3,  4,  6,  4, 10,  5,  4,  2,
        6,  1,  5,  6,  4,  4,  6,  6,  5,  2,  6,  6,  6,  6, 10,  2,  8,
        6,  5,  1,  6,  5,  5,  5,  7,  9,  3,  5,  3,  5,  2,  4,  3,  5,
        4,  5,  2,  4,  4,  6,  3,  6,  1,  5,  3,  4,  4,  6,  4,  4,  2,
        2,  3,  2,  6,  3,  4,  5,  5,  1,  7,  2,  6,  4,  5,  8,  6,  9,
        4,  7,  4,  5,  3,  5,  6,  6,  5,  8,  3,  2,  5,  5,  5,  3,  1,
        2,  7,  7,  4,  4,  8,  5,  3,  4,  2,  2,  3,  8,  2,  5,  6, 10,
        7,  5,  5,  1,  2,  3,  4,  5,  5,  3,  2,  2,  4,  6,  6,  3,  4,
        2,  3,  3,  9,  5,  1,  6,  5,  4,  5, 10,  0,  6,  2,  7,  9,  5,
        7,  6,  7,  5,  2

In [48]:
arr = ['a', 'b', 'c', 'd', 'e']
np.random.choice(arr, 4, (0.1, 0, 0.3, 0.6, 0))

array(['e', 'a', 'b', 'c'], dtype='<U1')