In [2]:
# array函数
import numpy as np
a = np.array([1,2,3])
a = np.array([[1,2],[3,4]])
a = np.array([1,2,3], dtype = complex)    

In [3]:
# zeros函数
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
# ones函数
np.ones((2,3))


array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
# eye函数
np.eye(10)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [6]:
# arange函数
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# NumPy数据类型举例
a = np.array([1,2,3], dtype=np.float64)
a = np.array([1,2,3], dtype=np.int32)
a = np.array(['abc', 'defg'], dtype=np.string_)

In [8]:
# 对数据进行批量运算，不需要写循环
a = np.array([1,2,3])
print(a * a)
print(a + a)
print(1/a)

a=np.arange(10)
print(np.sqrt(a))
print(np.exp(a))

b=np.random.randn(10)
c = np.add(a, b)
d = np.maximum(b, c)

[1 4 9]
[2 4 6]
[1.         0.5        0.33333333]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [9]:
# 一维数组
arr = np.arange(10)
arr[5:8] # 切片
arr[5:8] = 12 # 赋值

# 高维数组
arr2d = np.arange(9).reshape((3,3))
arr2d[2] # 输出一维数组
arr2d[0][2]
arr2d[0, 2]

2

In [10]:
# 数据统计
arr = np.array([3, 2, 4, 1])
arr.mean() # 计算平均值
arr.sum() # 求和
arr.std() # 计算方差
arr.min() # 求最小值
arr.argmin() # 求最小值的索引
arr.cumsum() # 累积求和
(arr>1).sum() # 大于1的个数
(arr>1).any() # 是否存在大于1的元素
(arr>1).all() # 是否所有元素都大于1

False

In [11]:
# 随机数生成

a = np.random.randn(3, 4) # 标准正态分布
a = np.random.randint(10, size=5) # 整数
a = np.random.poisson(5, 1000) # 泊松分布

arr = ['a', 'b', 'c', 'd', 'e']
np.random.choice(a, 4, (0.1, 0, 0.3, 0.6))

array([3, 3, 4, 4])

In [12]:
# 实战数据
np.random.seed(1)
values = np.random.randn(1000).cumsum()

array([ 1.62434536,  1.01258895,  0.4844172 , -0.58855142,  0.2768562 ,
       -2.02468249, -0.27987073, -1.04107763, -0.72203853, -0.97140891,
        0.49069903, -1.56944168, -1.89185888, -2.27591324, -1.1421438 ,
       -2.24203506, -2.41446327, -3.29232169, -3.25010794, -2.66729273,
       -3.76791191, -2.6231882 , -1.72159748, -1.21910314, -0.31824719,
       -1.00197505, -1.12486527, -2.06063471, -2.32852279, -1.79816732,
       -2.48982807, -2.8865816 , -3.5737543 , -4.41895994, -5.09020607,
       -5.10287067, -6.22018102, -5.98576532, -4.32596314, -3.58391898,
       -3.77575454, -4.6633835 , -5.41054179, -3.71808719, -3.66727944,
       -4.30427508, -4.1133596 , -2.01310446, -1.89294551, -1.2757424 ,
       -0.97557208, -1.32782193, -2.47034012, -2.81968285, -3.02857708,
       -2.44195389, -1.60297048, -0.67186839, -0.38628107,  0.4988601 ,
       -0.25553785,  0.99733031,  1.51026013,  1.21216729,  1.70068544,
        1.62511373,  2.75674312,  4.27655993,  6.46213534,  5.06

In [19]:
# 实现
i = np.argmax(np.maximum.accumulate(values) - values)
j = np.argmax(values[:i+1])
print(i, j)

790 599
